### PR TITLE
adding conversion from fp32 to int16

### PR DESCRIPTION
**Pull request by LakshmiKumar23**

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 few minor errors to fix with this PR

1. CMakeList Fix - RPi does not understand c++ flags
```
[ 16%] Building CXX object CMakeFiles/annmodule.dir/annmodule.cpp.o
c++: error: unrecognized command line option ‘-mf16c’
c++: error: unrecognized command line option ‘-mf16c’
make[2]: *** [CMakeFiles/annmodule.dir/build.make:63: CMakeFiles/annmodule.dir/annmodule.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/annmodule.dir/all] Error 2
```

2. Intrinsic code to be replaced with plane c code for RPi
```
-- OPENVX_INCLUDES: 	/home/pi/khronos/demo/OpenVX-sample-impl/install/Linux/x32/Debug/include
-- OPENVX_LIBRARIES: 	/home/pi/khronos/demo/OpenVX-sample-impl/install/Linux/x32/Debug/bin/libopenvx.so;/home/pi/khronos/demo/OpenVX-sample-impl/install/Linux/x32/Debug/bin/libvxu.so;pthread;dl;m;rt
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/khronos/demo/build
[ 16%] Building CXX object CMakeFiles/annmodule.dir/annmodule.cpp.o
[ 33%] Linking CXX shared library libannmodule.so
[ 33%] Built target annmodule
Scanning dependencies of target annpython
[ 50%] Building CXX object CMakeFiles/annpython.dir/annpython.cpp.o
[ 66%] Linking CXX shared library libannpython.so
[ 66%] Built target annpython
Scanning dependencies of target anntest
[ 83%] Building CXX object CMakeFiles/anntest.dir/anntest.cpp.o
/home/pi/khronos/demo/mnist-openvx/anntest.cpp:39:10: fatal error: immintrin.h: No such file or directory
 #include <immintrin.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/anntest.dir/build.make:63: CMakeFiles/anntest.dir/anntest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/anntest.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```

3. Replace intrin code
```
pi@raspberrypi:~/khronos/demo/build $ make
[ 33%] Built target annmodule
[ 66%] Built target annpython
Scanning dependencies of target anntest
[ 83%] Building CXX object CMakeFiles/anntest.dir/anntest.cpp.o
/home/pi/khronos/demo/mnist-openvx/anntest.cpp: In function ‘vx_status copyTensor(std::__cxx11::string, vx_tensor, std::__cxx11::string, vx_enum, std::__cxx11::string, std::__cxx11::string)’:
/home/pi/khronos/demo/mnist-openvx/anntest.cpp:278:33: error: ‘_cvtsh_ss’ was not declared in this scope
                     float src = _cvtsh_ss(((unsigned short*)ptr)[i]);
                                 ^~~~~~~~~
make[2]: *** [CMakeFiles/anntest.dir/build.make:63: CMakeFiles/anntest.dir/anntest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/anntest.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

4. Int16 error

```
pi@raspberrypi:~/khronos/demo/build $ ./anntest ../mnist-openvx/weights.bin 
ERROR: vxCreateTensor() failed for data
```

Test with sample on [Linux - Ubuntu 18.04](https://github.com/KhronosGroup/OpenVX-sample-impl#sample-1---build-openvx-13-on-ubuntu-1804)

**Comment by kiritigowda** [comment]
@LakshmiKumar23 here is the link to OpenVX sample CNN implementation - https://github.com/KhronosGroup/OpenVX-sample-impl/blob/openvx_1.3/sample/cnn/cnn_network/network.cpp#L334

**Comment by kiritigowda** [comment]
@LakshmiKumar23 any updates on this? we need to merge this.

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 few minor errors to fix with this PR
> 
> 1. CMakeList Fix - RPi does not understand c++ flags
> 
> ```
> [ 16%] Building CXX object CMakeFiles/annmodule.dir/annmodule.cpp.o
> c++: error: unrecognized command line option ‘-mf16c’
> c++: error: unrecognized command line option ‘-mf16c’
> make[2]: *** [CMakeFiles/annmodule.dir/build.make:63: CMakeFiles/annmodule.dir/annmodule.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/annmodule.dir/all] Error 2
> ```
> 
@kiritigowda Not sure what these flags are meant for. No documentation online. I have removed them completely. I think they might be FP16 flags.
> 1. Intrinsic code to be replaced with plane c code for RPi
> 
> ```
> -- OPENVX_INCLUDES: 	/home/pi/khronos/demo/OpenVX-sample-impl/install/Linux/x32/Debug/include
> -- OPENVX_LIBRARIES: 	/home/pi/khronos/demo/OpenVX-sample-impl/install/Linux/x32/Debug/bin/libopenvx.so;/home/pi/khronos/demo/OpenVX-sample-impl/install/Linux/x32/Debug/bin/libvxu.so;pthread;dl;m;rt
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/pi/khronos/demo/build
> [ 16%] Building CXX object CMakeFiles/annmodule.dir/annmodule.cpp.o
> [ 33%] Linking CXX shared library libannmodule.so
> [ 33%] Built target annmodule
> Scanning dependencies of target annpython
> [ 50%] Building CXX object CMakeFiles/annpython.dir/annpython.cpp.o
> [ 66%] Linking CXX shared library libannpython.so
> [ 66%] Built target annpython
> Scanning dependencies of target anntest
> [ 83%] Building CXX object CMakeFiles/anntest.dir/anntest.cpp.o
> /home/pi/khronos/demo/mnist-openvx/anntest.cpp:39:10: fatal error: immintrin.h: No such file or directory
>  #include <immintrin.h>
>           ^~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [CMakeFiles/anntest.dir/build.make:63: CMakeFiles/anntest.dir/anntest.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/anntest.dir/all] Error 2
> make: *** [Makefile:84: all] Error 2
> ```
> @kiritigowda Commenting out the intrinsic code because it shouldn't go into that  'if-else' branch. 'If' branch is only for float16
> 1. Replace intrin code
> 
> ```
> pi@raspberrypi:~/khronos/demo/build $ make
> [ 33%] Built target annmodule
> [ 66%] Built target annpython
> Scanning dependencies of target anntest
> [ 83%] Building CXX object CMakeFiles/anntest.dir/anntest.cpp.o
> /home/pi/khronos/demo/mnist-openvx/anntest.cpp: In function ‘vx_status copyTensor(std::__cxx11::string, vx_tensor, std::__cxx11::string, vx_enum, std::__cxx11::string, std::__cxx11::string)’:
> /home/pi/khronos/demo/mnist-openvx/anntest.cpp:278:33: error: ‘_cvtsh_ss’ was not declared in this scope
>                      float src = _cvtsh_ss(((unsigned short*)ptr)[i]);
>                                  ^~~~~~~~~
> make[2]: *** [CMakeFiles/anntest.dir/build.make:63: CMakeFiles/anntest.dir/anntest.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/anntest.dir/all] Error 2
> make: *** [Makefile:84: all] Error 2
> ```
> @kiritigowda Commenting out the intrinsic code because it shouldn't go into that 'if-else' branch. The 'If' branch is only for float16
> 1. Int16 error
> 
> ```
> pi@raspberrypi:~/khronos/demo/build $ ./anntest ../mnist-openvx/weights.bin 
> ERROR: vxCreateTensor() failed for data
> ```
> @kiritigowda I don't understand why this is happening. Because when we checked last time, if you remember the sample implementation said it supported INT16. That's why we decided to convert it. The vxCreateTensor() API under sample implementation supports INT16.
> Test with sample on [Linux - Ubuntu 18.04](https://github.com/KhronosGroup/OpenVX-sample-impl#sample-1---build-openvx-13-on-ubuntu-1804)

**Comment by LakshmiKumar23** [comment]
@kiritigowda Updated PR and please see above for comments

**Review by kiritigowda — APPROVED** [review]

**Pull request merged**
